
CC=cl.exe
AR=lib.exe

CFLAGS =  /nologo /I src /I src\blake2 /I include

!if "$(DEBUG)" == "1"
CFLAGS = $(CFLAGS)
OUT_LIB_NAME = argon2ref_a_debug.lib
!else
CFLAGS = $(CFLAGS)
OUT_LIB_NAME = argon2ref_a.lib
!endif


all:
	$(CC) $(CFLAGS) /c src\argon2.c src\core.c src\blake2\blake2b.c src\thread.c src\encoding.c src\ref.c
	$(AR) /OUT:$(OUT_LIB_NAME) argon2.obj core.obj blake2b.obj thread.obj encoding.obj ref.obj

clean:
	del *.obj *.lib

